#include <iostream>
#include <vector>
#include <random>

/* Create a new program that will create a vector of 
 * random size, filled with random numbers between 1 
 * and 100.*/

int main() {
    std::vector<int> v;
    std::random_device rd;  // A seed source for the random number engine
    std::mt19937 gen(rd());  // Mersenne_twister_engine seeded with rd()
    std::uniform_int_distribution<> distrib(1, 100);
    // Use distrib to transform the random unsigned int
    // generated by gen into an int in [1, 100]
    for (int n = 0; n != INT16_MAX; ++n) {
        v.push_back(distrib(gen));
        std::cout << v[n] << " ";
    }
    std::cout << "\n";
    return 0;
}